name: Tidy

on:
  push:
    # Run every time a shell script changes
    paths:
      - '**/*.sh'
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        run: |
          sudo apt-get install -y shellcheck
          make lint

